import pointsLogo from '../images/pointsLOGO.png'
import { PointsDetails } from '../types/types'

export const listOfImages: Array<PointsDetails> = [
    {
        id: 101,
        src: pointsLogo,
        name: "Let's go !",
        description: 'Start the survey',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 102,
        src: pointsLogo,
        name: "33% Achieved",
        description: 'Answer 33% of the questions',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 103,
        src: pointsLogo,
        name: "Sherlock Holmes",
        description: 'Find the mascot',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 104,
        src: pointsLogo,
        name: "66% Achieved",
        description: 'Answer 66% of the questions',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 105,
        src: pointsLogo,
        name: "Fast Achiever",
        description: 'Reach the last 5 questions',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 106,
        src: pointsLogo,
        name: "Master of Interview",
        description: 'Answer the interview questions',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 107,
        src: pointsLogo,
        name: "Winner",
        description: 'Complete the survey',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 108,
        src: pointsLogo,
        name: "Full Points",
        description: 'Answer all questions including the open ones',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 109,
        src: pointsLogo,
        name: "Tactician",
        description: 'Takes at least 3 minutes for each page',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 110,
        src: pointsLogo,
        name: "Medal Collector",
        description: 'Collect all badges',
        isAchieved: false,
        isNotified: false,
    },
]

export const listOfMockImages: Array<PointsDetails> = [
    {
        id: 201,
        src: pointsLogo,
        name: "Head-start",
        description: 'Start the survey',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 202,
        src: pointsLogo,
        name: "Pusher",
        description: 'Answer 33% of the questions',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 203,
        src: pointsLogo,
        name: "With a purpose",
        description: 'Find the mascot',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 204,
        src: pointsLogo,
        name: "Go-getter",
        description: 'Answer 66% of the questions',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 205,
        src: pointsLogo,
        name: "Reacher",
        description: 'Reach the last 5 questions',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 206,
        src: pointsLogo,
        name: "I am a Star",
        description: 'Answer the interview questions',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 207,
        src: pointsLogo,
        name: "Winner",
        description: 'Complete the survey',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 208,
        src: pointsLogo,
        name: "Full Points",
        description: 'Answer all questions including the open ones',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 209,
        src: pointsLogo,
        name: "Grandmaster",
        description: 'Takes at least 30 seconds for each question',
        isAchieved: false,
        isNotified: false,
    },
    {
        id: 210,
        src: pointsLogo,
        name: "Midas touch",
        description: 'Collect all badges',
        isAchieved: false,
        isNotified: false,
    },
]